services:
  db:
    image: mysql:8
    container_name: clima-api-db-1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: clima_db
      MYSQL_USER: clima_user
      MYSQL_PASSWORD: clima_pass
    ports:
      - "3310:3306"
    volumes:
      - db_data:/var/lib/mysql

  api:
    build: .
    container_name: clima-api-api-1
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_NAME: clima_db
      DATABASE_USER: clima_user
      DATABASE_PASSWORD: clima_pass

volumes:
  db_data:
