version: "3.8"

services:
  db:
    image: mysql:8
    
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: clima_db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3310:3306"

  api:
    build: .
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  db_data:
