version: "3.8"

services:
  db:
    image: mysql:8
    
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: clima_db
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3310:3306"

  api:
    build: .
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: clima_db
      DATABASE_PORT: 3310

volumes:
  db_data:
